### ISSUE TITLE
Where is the affine transformation "A" ?

### ISSUE THREAD

**Issue by songquanpeng** [makeuptransfer/SCGAN#12]
Firstly thx for public your code implementation.

I have a question about the implementation of the affine transformation:
![image](https://user-images.githubusercontent.com/39998050/127336349-0a860126-30f6-4b39-ab43-7788c66c1b30.png)

The style code is sent into 3 different "A" here. But I have checked the code and I couldn't find the corresponding implementation.

https://github.com/makeuptransfer/SCGAN/blob/5f5018969c33a4e309c82f273b88ddb0ba3a17f0/models/SCGen.py#L121-L125

Looks like after the MLP procession, the codes are directly sent into the MFDec as the corresponding mean & std:
https://github.com/makeuptransfer/SCGAN/blob/5f5018969c33a4e309c82f273b88ddb0ba3a17f0/models/SCGen.py#L127-L136

**Comment by makeuptransfer** [comment]
MLP do the same computation as affine transformation：AX+B
