### ISSUE TITLE
Add description of parsing and face alignment

### ISSUE THREAD

**Issue by salvadog** [makeuptransfer/SCGAN#2]
Thanks for sharing your work! A description of parsing method + label defination and face alignment method is needed.

**Comment by tommy19970714** [comment]
I analyzed the RGB values of the [segmentation](https://github.com/makeuptransfer/SCGAN/blob/master/MT-Dataset/parsing/non-makeup/xfsy_0444.png) uploaded to this repo and created a map to parse it.
You can use the parser by changing the following line of PSGAN to the following code.
https://github.com/wtjiang98/PSGAN/blob/33f246c8b4cf616929c01963476eb0d3f9d57132/faceutils/mask/main.py#L16

```
mapper = [0, 4, 7, 2, 6, 1, 0, 3, 5, 0, 8, 11, 9, 13, 10, 0, 0, 12, 0]
```
