### ISSUE TITLE
face parser Out of order

### ISSUE THREAD

**Issue by cshopping** [makeuptransfer/SCGAN#22]
First of all thank you for your excellent work. this is a cool paper, but i have a question

The attribute id after your example is neither the same as the result of [face_parser](https://github.com/zllrunning/face-parsing.PyTorch.git), nor the same order as psgan after modifying the mapper, can you tell me the order you use when training, for example:
     # atts = [1 'skin', 2 'l_brow', 3 'r_brow', 4 'l_eye', 5 'r_eye', 6 'eye_g', 7 'l_ear', 8 'r_ear', 9 'ear_r',
        #         10 'nose', 11 'mouth', 12 'u_lip', 13 'l_lip', 14 'neck', 15 'neck_l', 16 'cloth', 17 'hair', 18 'hat']

The first is the result of the sample you gave, which is the same as (SCDataset imp), and the next is the result processed with [parser-face](https://github.com/zllrunning/face-parsing.PyTorch.git)
![2](https://user-images.githubusercontent.com/20111765/154469027-1f35cc49-f9fc-4060-8b2c-e034880ebca0.png)
![3](https://user-images.githubusercontent.com/20111765/154469503-5a4caf30-6d0a-45f2-841f-be9574a3114e.png)
:

**Comment by cshopping** [comment]
run script/handle_parsing.py also can't be modified to be the same as the sample you gave.

**Comment by makeuptransfer** [comment]
you can run script/handle_parsing.py with the labels provided by the makeup transfer dataset directly
