### ISSUE TITLE
是否需要一些预处理操作，才能生成合理的结果？

### ISSUE THREAD

**Issue by DWCTOD** [makeuptransfer/SCGAN#3]
你好，感谢你们的工作，这是我尝试的结果，感觉效果并不是非常的理想，不知道是否需要一些预处理操作。
![image](https://user-images.githubusercontent.com/41478810/123600644-73068d00-d829-11eb-8813-bc92f15af5a3.png)

**Comment by makeuptransfer** [comment]
把头像部位crop出来试试看，我估计因为是因为训练集都是头像所以这种情况可能需要crop出头像来再transfer会好一点
