### ISSUE TITLE
Can not reproduce the results using pretrained model

### ISSUE THREAD

**Issue by Gymat** [makeuptransfer/SCGAN#6]
Hi, thanks for sharing the code. I run the global makeup transfer with provided pretrained model, but I can not reproduce the results. 
I ran the code, and the obtain the results as below:
![global_transferred](https://user-images.githubusercontent.com/14540448/125761644-0b662b3d-0564-47a7-b614-73098580e3b4.jpg)

The results is totally incorrect, and I don't know why.

**Comment by Gymat** [comment]
I check the pretrained model path, put the G.pth in the right place, and obtain the correct result.

**Comment by Xiaoyang-Rebecca** [comment]
I have the same issue for testing. Seem that the testing code need normalization or so
