### ISSUE TITLE
Re-train a model using default args but the transferred output looks incorrect

### ISSUE THREAD

**Issue by PennyPeng369** [makeuptransfer/SCGAN#9]
Hi, I tried to retrain a model using code and args in default of this repo. However, the inference output looks incorrect. 
I don't know why the transferred images are very fuzzy and ambiguous. 
Any suggestion would be appreciated. Thanks.

![global_transferred](https://user-images.githubusercontent.com/13273334/126123372-64cb9bb1-be8a-4c7b-9d8a-29599ed7014e.jpg)

**Comment by makeuptransfer** [comment]
did u rewrite the trainlist？

**Comment by PennyPeng369** [comment]
> did u rewrite the trainlist？

I used the makeup.txt and non-makeup.txt provided by PSGAN(https://github.com/wtjiang98/PSGAN).

**Comment by PennyPeng369** [comment]
> did u rewrite the trainlist？

By the way, can you apply

**Comment by PennyPeng369** [comment]
> did u rewrite the trainlist？

By the way, can you open the trainlist used for this project? thanks:)

**Comment by makeuptransfer** [comment]
see hong bo's question
